//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ssi.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("login")]
        public string MongoDBUser {
            get {
                return ((string)(this["MongoDBUser"]));
            }
            set {
                this["MongoDBUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("password")]
        public string MongoDBPass {
            get {
                return ((string)(this["MongoDBPass"]));
            }
            set {
                this["MongoDBPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sftp.server.yeah")]
        public string DataServer {
            get {
                return ((string)(this["DataServer"]));
            }
            set {
                this["DataServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/path/to/your/files/")]
        public string DataServerFolder {
            get {
                return ((string)(this["DataServerFolder"]));
            }
            set {
                this["DataServerFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DataServerLogin {
            get {
                return ((string)(this["DataServerLogin"]));
            }
            set {
                this["DataServerLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DataServerPass {
            get {
                return ((string)(this["DataServerPass"]));
            }
            set {
                this["DataServerPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sftp")]
        public string DataServerConnectionType {
            get {
                return ((string)(this["DataServerConnectionType"]));
            }
            set {
                this["DataServerConnectionType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSessionId {
            get {
                return ((string)(this["LastSessionId"]));
            }
            set {
                this["LastSessionId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost:27017")]
        public string DatabaseAddress {
            get {
                return ((string)(this["DatabaseAddress"]));
            }
            set {
                this["DatabaseAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DatabaseName {
            get {
                return ((string)(this["DatabaseName"]));
            }
            set {
                this["DatabaseName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DatabaseDirectory {
            get {
                return ((string)(this["DatabaseDirectory"]));
            }
            set {
                this["DatabaseDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DatabaseAutoLogin {
            get {
                return ((bool)(this["DatabaseAutoLogin"]));
            }
            set {
                this["DatabaseAutoLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.7")]
        public double UncertaintyLevel {
            get {
                return ((double)(this["UncertaintyLevel"]));
            }
            set {
                this["UncertaintyLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Annotator")]
        public string Annotator {
            get {
                return ((string)(this["Annotator"]));
            }
            set {
                this["Annotator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double DefaultZoomInSeconds {
            get {
                return ((double)(this["DefaultZoomInSeconds"]));
            }
            set {
                this["DefaultZoomInSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double DefaultMinSegmentSize {
            get {
                return ((double)(this["DefaultMinSegmentSize"]));
            }
            set {
                this["DefaultMinSegmentSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public double DefaultDiscreteSampleRate {
            get {
                return ((double)(this["DefaultDiscreteSampleRate"]));
            }
            set {
                this["DefaultDiscreteSampleRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DatabaseShowOnlyMine {
            get {
                return ((bool)(this["DatabaseShowOnlyMine"]));
            }
            set {
                this["DatabaseShowOnlyMine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DatabaseShowOnlyFinished {
            get {
                return ((bool)(this["DatabaseShowOnlyFinished"]));
            }
            set {
                this["DatabaseShowOnlyFinished"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int CMLContext {
            get {
                return ((int)(this["CMLContext"]));
            }
            set {
                this["CMLContext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string CMLDefaultAnnotator {
            get {
                return ((string)(this["CMLDefaultAnnotator"]));
            }
            set {
                this["CMLDefaultAnnotator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string CMLDefaultScheme {
            get {
                return ((string)(this["CMLDefaultScheme"]));
            }
            set {
                this["CMLDefaultScheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string CMLDefaultRole {
            get {
                return ((string)(this["CMLDefaultRole"]));
            }
            set {
                this["CMLDefaultRole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CMLSetConf {
            get {
                return ((bool)(this["CMLSetConf"]));
            }
            set {
                this["CMLSetConf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CMLRemove {
            get {
                return ((bool)(this["CMLRemove"]));
            }
            set {
                this["CMLRemove"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CMLFill {
            get {
                return ((bool)(this["CMLFill"]));
            }
            set {
                this["CMLFill"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckUpdateOnStart {
            get {
                return ((bool)(this["CheckUpdateOnStart"]));
            }
            set {
                this["CheckUpdateOnStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string CMLDefaultStream {
            get {
                return ((string)(this["CMLDefaultStream"]));
            }
            set {
                this["CMLDefaultStream"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double CMLDefaultConf {
            get {
                return ((double)(this["CMLDefaultConf"]));
            }
            set {
                this["CMLDefaultConf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double CMLDefaultGap {
            get {
                return ((double)(this["CMLDefaultGap"]));
            }
            set {
                this["CMLDefaultGap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.15")]
        public double CMLDefaultMinDur {
            get {
                return ((double)(this["CMLDefaultMinDur"]));
            }
            set {
                this["CMLDefaultMinDur"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DatabaseAskBeforeOverwrite {
            get {
                return ((bool)(this["DatabaseAskBeforeOverwrite"]));
            }
            set {
                this["DatabaseAskBeforeOverwrite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1979-01-01")]
        public global::System.DateTime LastUpdateCheckDate {
            get {
                return ((global::System.DateTime)(this["LastUpdateCheckDate"]));
            }
            set {
                this["LastUpdateCheckDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ContinuousHotkeysNumber {
            get {
                return ((int)(this["ContinuousHotkeysNumber"]));
            }
            set {
                this["ContinuousHotkeysNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LiveModeActivateMouse {
            get {
                return ((bool)(this["LiveModeActivateMouse"]));
            }
            set {
                this["LiveModeActivateMouse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LOW;MEDIUM;HIGH")]
        public string ConvertToDiscreteClasses {
            get {
                return ((string)(this["ConvertToDiscreteClasses"]));
            }
            set {
                this["ConvertToDiscreteClasses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.33;0.66;1.0")]
        public string ConvertToDiscreteThreshs {
            get {
                return ((string)(this["ConvertToDiscreteThreshs"]));
            }
            set {
                this["ConvertToDiscreteThreshs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0")]
        public string ConvertToDiscreteDelays {
            get {
                return ((string)(this["ConvertToDiscreteDelays"]));
            }
            set {
                this["ConvertToDiscreteDelays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string CMLDefaultTrainer {
            get {
                return ((string)(this["CMLDefaultTrainer"]));
            }
            set {
                this["CMLDefaultTrainer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CMLDirectory {
            get {
                return ((string)(this["CMLDirectory"]));
            }
            set {
                this["CMLDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000")]
        public string CMLTrainexeGitSha {
            get {
                return ((string)(this["CMLTrainexeGitSha"]));
            }
            set {
                this["CMLTrainexeGitSha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DBHideMissingStreams {
            get {
                return ((bool)(this["DBHideMissingStreams"]));
            }
            set {
                this["DBHideMissingStreams"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CMLDefaultChain {
            get {
                return ((string)(this["CMLDefaultChain"]));
            }
            set {
                this["CMLDefaultChain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CMLDefaultAnnotatorPrediction {
            get {
                return ((string)(this["CMLDefaultAnnotatorPrediction"]));
            }
            set {
                this["CMLDefaultAnnotatorPrediction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SettingCMLDefaultBN {
            get {
                return ((string)(this["SettingCMLDefaultBN"]));
            }
            set {
                this["SettingCMLDefaultBN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DrawVideoWavform {
            get {
                return ((bool)(this["DrawVideoWavform"]));
            }
            set {
                this["DrawVideoWavform"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string explainModelPath {
            get {
                return ((string)(this["explainModelPath"]));
            }
            set {
                this["explainModelPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost:27017")]
        public string serverhistory {
            get {
                return ((string)(this["serverhistory"]));
            }
            set {
                this["serverhistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool forcepythonupdate {
            get {
                return ((bool)(this["forcepythonupdate"]));
            }
            set {
                this["forcepythonupdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnablePython {
            get {
                return ((bool)(this["EnablePython"]));
            }
            set {
                this["EnablePython"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CMLTempTrainerPath {
            get {
                return ((string)(this["CMLTempTrainerPath"]));
            }
            set {
                this["CMLTempTrainerPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnablePythonDebug {
            get {
                return ((bool)(this["EnablePythonDebug"]));
            }
            set {
                this["EnablePythonDebug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public string CMLTempTrainerName {
            get {
                return ((string)(this["CMLTempTrainerName"]));
            }
            set {
                this["CMLTempTrainerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableLightning {
            get {
                return ((bool)(this["EnableLightning"]));
            }
            set {
                this["EnableLightning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public double DefaultPolygonPointDistance {
            get {
                return ((double)(this["DefaultPolygonPointDistance"]));
            }
            set {
                this["DefaultPolygonPointDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hardware")]
        public string MediaBackend {
            get {
                return ((string)(this["MediaBackend"]));
            }
            set {
                this["MediaBackend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowExportDatabase {
            get {
                return ((bool)(this["ShowExportDatabase"]));
            }
            set {
                this["ShowExportDatabase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LoggedInWithLightning {
            get {
                return ((bool)(this["LoggedInWithLightning"]));
            }
            set {
                this["LoggedInWithLightning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SRTwordlevel {
            get {
                return ((bool)(this["SRTwordlevel"]));
            }
            set {
                this["SRTwordlevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost:27017")]
        public string NovaServerHistory {
            get {
                return ((string)(this["NovaServerHistory"]));
            }
            set {
                this["NovaServerHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost:27017")]
        public string NovaServerAddress {
            get {
                return ((string)(this["NovaServerAddress"]));
            }
            set {
                this["NovaServerAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NovaAssistantAddress {
            get {
                return ((string)(this["NovaAssistantAddress"]));
            }
            set {
                this["NovaAssistantAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost:1337")]
        public string NovaAssistantHistory {
            get {
                return ((string)(this["NovaAssistantHistory"]));
            }
            set {
                this["NovaAssistantHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8")]
        public string NovaAssistantTemperature {
            get {
                return ((string)(this["NovaAssistantTemperature"]));
            }
            set {
                this["NovaAssistantTemperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Your name is Nova Assistant. You are an AI assistant.")]
        public string NovaAssistantSystemPrompt {
            get {
                return ((string)(this["NovaAssistantSystemPrompt"]));
            }
            set {
                this["NovaAssistantSystemPrompt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024")]
        public string NovaAssistantMaxtokens {
            get {
                return ((string)(this["NovaAssistantMaxtokens"]));
            }
            set {
                this["NovaAssistantMaxtokens"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string NovaAssistantTopK {
            get {
                return ((string)(this["NovaAssistantTopK"]));
            }
            set {
                this["NovaAssistantTopK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.95")]
        public string NovaAssistantTopP {
            get {
                return ((string)(this["NovaAssistantTopP"]));
            }
            set {
                this["NovaAssistantTopP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The data you are supposed to analyse is provided to you in semi colon seperated t" +
            "uple form, where each entry contains the identity of the speaker at position 0 a" +
            "nd the transcript of a speaker at position 1")]
        public string NovaAssistantDataDescription {
            get {
                return ((string)(this["NovaAssistantDataDescription"]));
            }
            set {
                this["NovaAssistantDataDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hcai:llama7b")]
        public string NovaAssistantModel {
            get {
                return ((string)(this["NovaAssistantModel"]));
            }
            set {
                this["NovaAssistantModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NovaAssistantEnforceDeterminism {
            get {
                return ((bool)(this["NovaAssistantEnforceDeterminism"]));
            }
            set {
                this["NovaAssistantEnforceDeterminism"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NostrDVM {
            get {
                return ((bool)(this["NostrDVM"]));
            }
            set {
                this["NostrDVM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2028")]
        public string NovaAssistantNum_ctx {
            get {
                return ((string)(this["NovaAssistantNum_ctx"]));
            }
            set {
                this["NovaAssistantNum_ctx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseTLS {
            get {
                return ((bool)(this["UseTLS"]));
            }
            set {
                this["UseTLS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SignedCertificatesOnly {
            get {
                return ((bool)(this["SignedCertificatesOnly"]));
            }
            set {
                this["SignedCertificatesOnly"] = value;
            }
        }
    }
}
